// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: conversation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Conversation {

  /// <summary>Holder for reflection information generated from conversation.proto</summary>
  public static partial class ConversationReflection {

    #region Descriptor
    /// <summary>File descriptor for conversation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConversationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJjb252ZXJzYXRpb24ucHJvdG8SDGNvbnZlcnNhdGlvbiIzCgZTdGF0dXMS",
            "DgoGbnVtYmVyGAEgASgDEgwKBGNvZGUYAiABKAUSCwoDbXNnGAMgASgJIogF",
            "ChBDb252ZXJzYXRpb25MaXN0EiQKBnN0YXR1cxgBIAEoCzIULmNvbnZlcnNh",
            "dGlvbi5TdGF0dXMSPQoEZGF0YRgCIAMoCzIvLmNvbnZlcnNhdGlvbi5Db252",
            "ZXJzYXRpb25MaXN0LkNvbnZlcnNhdGlvbkRhdGESDQoFdG90YWwYAyABKAUS",
            "EgoKcmVxdWVzdF9pZBgEIAEoCRrrAwoQQ29udmVyc2F0aW9uRGF0YRIPCgdj",
            "aGF0X2lkGAEgASgJEhEKCWNoYXRfdHlwZRgCIAEoBRIMCgRuYW1lGAMgASgJ",
            "EhQKDGNoYXRfY29udGVudBgEIAEoCRIUCgx0aW1lc3RhbXBfbXMYBSABKAMS",
            "FgoOdW5yZWFkX21lc3NhZ2UYBiABKAUSCgoCYXQYByABKAUSEQoJYXZhdGFy",
            "X2lkGAggASgDEhIKCmF2YXRhcl91cmwYCSABKAkSFgoOZG9fbm90X2Rpc3R1",
            "cmIYCyABKAUSEQoJdGltZXN0YW1wGAwgASgDEkcKB2F0X2RhdGEYDiABKAsy",
            "Ni5jb252ZXJzYXRpb24uQ29udmVyc2F0aW9uTGlzdC5Db252ZXJzYXRpb25E",
            "YXRhLkF0RGF0YRIbChNjZXJ0aWZpY2F0aW9uX2xldmVsGBAgASgFGpwBCgZB",
            "dERhdGESDwoHdW5rbm93bhgBIAEoAxIUCgxtZW50aW9uZWRfaWQYAiABKAkS",
            "FgoObWVudGlvbmVkX25hbWUYAyABKAkSFAoMbWVudGlvbmVkX2luGAQgASgJ",
            "EhQKDG1lbnRpb25lcl9pZBgGIAEoCRIWCg5tZW50aW9uZXJfbmFtZRgHIAEo",
            "CRIPCgdtc2dfc2VxGAggASgDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Conversation.Status), global::Conversation.Status.Parser, new[]{ "Number", "Code", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Conversation.ConversationList), global::Conversation.ConversationList.Parser, new[]{ "Status", "Data", "Total", "RequestId" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Conversation.ConversationList.Types.ConversationData), global::Conversation.ConversationList.Types.ConversationData.Parser, new[]{ "ChatId", "ChatType", "Name", "ChatContent", "TimestampMs", "UnreadMessage", "At", "AvatarId", "AvatarUrl", "DoNotDisturb", "Timestamp", "AtData", "CertificationLevel" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Conversation.ConversationList.Types.ConversationData.Types.AtData), global::Conversation.ConversationList.Types.ConversationData.Types.AtData.Parser, new[]{ "Unknown", "MentionedId", "MentionedName", "MentionedIn", "MentionerId", "MentionerName", "MsgSeq" }, null, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 响应状态
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Status : pb::IMessage<Status>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Status> _parser = new pb::MessageParser<Status>(() => new Status());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Status> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Conversation.ConversationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status(Status other) : this() {
      number_ = other.number_;
      code_ = other.code_;
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status Clone() {
      return new Status(this);
    }

    /// <summary>Field number for the "number" field.</summary>
    public const int NumberFieldNumber = 1;
    private long number_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Number {
      get { return number_; }
      set {
        number_ = value;
      }
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 2;
    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Status);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Status other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Number != other.Number) return false;
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Number != 0L) hash ^= Number.GetHashCode();
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Number != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Number);
      }
      if (Code != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Code);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Number != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Number);
      }
      if (Code != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Code);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Number != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Number);
      }
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Status other) {
      if (other == null) {
        return;
      }
      if (other.Number != 0L) {
        Number = other.Number;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Number = input.ReadInt64();
            break;
          }
          case 16: {
            Code = input.ReadInt32();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Number = input.ReadInt64();
            break;
          }
          case 16: {
            Code = input.ReadInt32();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 列出对话
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ConversationList : pb::IMessage<ConversationList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConversationList> _parser = new pb::MessageParser<ConversationList>(() => new ConversationList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConversationList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Conversation.ConversationReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConversationList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConversationList(ConversationList other) : this() {
      status_ = other.status_ != null ? other.status_.Clone() : null;
      data_ = other.data_.Clone();
      total_ = other.total_;
      requestId_ = other.requestId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConversationList Clone() {
      return new ConversationList(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Conversation.Status status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Conversation.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Conversation.ConversationList.Types.ConversationData> _repeated_data_codec
        = pb::FieldCodec.ForMessage(18, global::Conversation.ConversationList.Types.ConversationData.Parser);
    private readonly pbc::RepeatedField<global::Conversation.ConversationList.Types.ConversationData> data_ = new pbc::RepeatedField<global::Conversation.ConversationList.Types.ConversationData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Conversation.ConversationList.Types.ConversationData> Data {
      get { return data_; }
    }

    /// <summary>Field number for the "total" field.</summary>
    public const int TotalFieldNumber = 3;
    private int total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 4;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConversationList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConversationList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Status, other.Status)) return false;
      if(!data_.Equals(other.data_)) return false;
      if (Total != other.Total) return false;
      if (RequestId != other.RequestId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (status_ != null) hash ^= Status.GetHashCode();
      hash ^= data_.GetHashCode();
      if (Total != 0) hash ^= Total.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (status_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Status);
      }
      data_.WriteTo(output, _repeated_data_codec);
      if (Total != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Total);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (status_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Status);
      }
      data_.WriteTo(ref output, _repeated_data_codec);
      if (Total != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Total);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RequestId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (status_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      size += data_.CalculateSize(_repeated_data_codec);
      if (Total != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Total);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConversationList other) {
      if (other == null) {
        return;
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Conversation.Status();
        }
        Status.MergeFrom(other.Status);
      }
      data_.Add(other.data_);
      if (other.Total != 0) {
        Total = other.Total;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (status_ == null) {
              Status = new global::Conversation.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 18: {
            data_.AddEntriesFrom(input, _repeated_data_codec);
            break;
          }
          case 24: {
            Total = input.ReadInt32();
            break;
          }
          case 34: {
            RequestId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (status_ == null) {
              Status = new global::Conversation.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 18: {
            data_.AddEntriesFrom(ref input, _repeated_data_codec);
            break;
          }
          case 24: {
            Total = input.ReadInt32();
            break;
          }
          case 34: {
            RequestId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ConversationList message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class ConversationData : pb::IMessage<ConversationData>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ConversationData> _parser = new pb::MessageParser<ConversationData>(() => new ConversationData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ConversationData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Conversation.ConversationList.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConversationData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConversationData(ConversationData other) : this() {
          chatId_ = other.chatId_;
          chatType_ = other.chatType_;
          name_ = other.name_;
          chatContent_ = other.chatContent_;
          timestampMs_ = other.timestampMs_;
          unreadMessage_ = other.unreadMessage_;
          at_ = other.at_;
          avatarId_ = other.avatarId_;
          avatarUrl_ = other.avatarUrl_;
          doNotDisturb_ = other.doNotDisturb_;
          timestamp_ = other.timestamp_;
          atData_ = other.atData_ != null ? other.atData_.Clone() : null;
          certificationLevel_ = other.certificationLevel_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ConversationData Clone() {
          return new ConversationData(this);
        }

        /// <summary>Field number for the "chat_id" field.</summary>
        public const int ChatIdFieldNumber = 1;
        private string chatId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ChatId {
          get { return chatId_; }
          set {
            chatId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "chat_type" field.</summary>
        public const int ChatTypeFieldNumber = 2;
        private int chatType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ChatType {
          get { return chatType_; }
          set {
            chatType_ = value;
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 3;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "chat_content" field.</summary>
        public const int ChatContentFieldNumber = 4;
        private string chatContent_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ChatContent {
          get { return chatContent_; }
          set {
            chatContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "timestamp_ms" field.</summary>
        public const int TimestampMsFieldNumber = 5;
        private long timestampMs_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long TimestampMs {
          get { return timestampMs_; }
          set {
            timestampMs_ = value;
          }
        }

        /// <summary>Field number for the "unread_message" field.</summary>
        public const int UnreadMessageFieldNumber = 6;
        private int unreadMessage_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int UnreadMessage {
          get { return unreadMessage_; }
          set {
            unreadMessage_ = value;
          }
        }

        /// <summary>Field number for the "at" field.</summary>
        public const int AtFieldNumber = 7;
        private int at_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int At {
          get { return at_; }
          set {
            at_ = value;
          }
        }

        /// <summary>Field number for the "avatar_id" field.</summary>
        public const int AvatarIdFieldNumber = 8;
        private long avatarId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long AvatarId {
          get { return avatarId_; }
          set {
            avatarId_ = value;
          }
        }

        /// <summary>Field number for the "avatar_url" field.</summary>
        public const int AvatarUrlFieldNumber = 9;
        private string avatarUrl_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string AvatarUrl {
          get { return avatarUrl_; }
          set {
            avatarUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "do_not_disturb" field.</summary>
        public const int DoNotDisturbFieldNumber = 11;
        private int doNotDisturb_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int DoNotDisturb {
          get { return doNotDisturb_; }
          set {
            doNotDisturb_ = value;
          }
        }

        /// <summary>Field number for the "timestamp" field.</summary>
        public const int TimestampFieldNumber = 12;
        private long timestamp_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long Timestamp {
          get { return timestamp_; }
          set {
            timestamp_ = value;
          }
        }

        /// <summary>Field number for the "at_data" field.</summary>
        public const int AtDataFieldNumber = 14;
        private global::Conversation.ConversationList.Types.ConversationData.Types.AtData atData_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Conversation.ConversationList.Types.ConversationData.Types.AtData AtData {
          get { return atData_; }
          set {
            atData_ = value;
          }
        }

        /// <summary>Field number for the "certification_level" field.</summary>
        public const int CertificationLevelFieldNumber = 16;
        private int certificationLevel_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CertificationLevel {
          get { return certificationLevel_; }
          set {
            certificationLevel_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ConversationData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ConversationData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ChatId != other.ChatId) return false;
          if (ChatType != other.ChatType) return false;
          if (Name != other.Name) return false;
          if (ChatContent != other.ChatContent) return false;
          if (TimestampMs != other.TimestampMs) return false;
          if (UnreadMessage != other.UnreadMessage) return false;
          if (At != other.At) return false;
          if (AvatarId != other.AvatarId) return false;
          if (AvatarUrl != other.AvatarUrl) return false;
          if (DoNotDisturb != other.DoNotDisturb) return false;
          if (Timestamp != other.Timestamp) return false;
          if (!object.Equals(AtData, other.AtData)) return false;
          if (CertificationLevel != other.CertificationLevel) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ChatId.Length != 0) hash ^= ChatId.GetHashCode();
          if (ChatType != 0) hash ^= ChatType.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (ChatContent.Length != 0) hash ^= ChatContent.GetHashCode();
          if (TimestampMs != 0L) hash ^= TimestampMs.GetHashCode();
          if (UnreadMessage != 0) hash ^= UnreadMessage.GetHashCode();
          if (At != 0) hash ^= At.GetHashCode();
          if (AvatarId != 0L) hash ^= AvatarId.GetHashCode();
          if (AvatarUrl.Length != 0) hash ^= AvatarUrl.GetHashCode();
          if (DoNotDisturb != 0) hash ^= DoNotDisturb.GetHashCode();
          if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
          if (atData_ != null) hash ^= AtData.GetHashCode();
          if (CertificationLevel != 0) hash ^= CertificationLevel.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ChatId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ChatId);
          }
          if (ChatType != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(ChatType);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Name);
          }
          if (ChatContent.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(ChatContent);
          }
          if (TimestampMs != 0L) {
            output.WriteRawTag(40);
            output.WriteInt64(TimestampMs);
          }
          if (UnreadMessage != 0) {
            output.WriteRawTag(48);
            output.WriteInt32(UnreadMessage);
          }
          if (At != 0) {
            output.WriteRawTag(56);
            output.WriteInt32(At);
          }
          if (AvatarId != 0L) {
            output.WriteRawTag(64);
            output.WriteInt64(AvatarId);
          }
          if (AvatarUrl.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(AvatarUrl);
          }
          if (DoNotDisturb != 0) {
            output.WriteRawTag(88);
            output.WriteInt32(DoNotDisturb);
          }
          if (Timestamp != 0L) {
            output.WriteRawTag(96);
            output.WriteInt64(Timestamp);
          }
          if (atData_ != null) {
            output.WriteRawTag(114);
            output.WriteMessage(AtData);
          }
          if (CertificationLevel != 0) {
            output.WriteRawTag(128, 1);
            output.WriteInt32(CertificationLevel);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ChatId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ChatId);
          }
          if (ChatType != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(ChatType);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Name);
          }
          if (ChatContent.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(ChatContent);
          }
          if (TimestampMs != 0L) {
            output.WriteRawTag(40);
            output.WriteInt64(TimestampMs);
          }
          if (UnreadMessage != 0) {
            output.WriteRawTag(48);
            output.WriteInt32(UnreadMessage);
          }
          if (At != 0) {
            output.WriteRawTag(56);
            output.WriteInt32(At);
          }
          if (AvatarId != 0L) {
            output.WriteRawTag(64);
            output.WriteInt64(AvatarId);
          }
          if (AvatarUrl.Length != 0) {
            output.WriteRawTag(74);
            output.WriteString(AvatarUrl);
          }
          if (DoNotDisturb != 0) {
            output.WriteRawTag(88);
            output.WriteInt32(DoNotDisturb);
          }
          if (Timestamp != 0L) {
            output.WriteRawTag(96);
            output.WriteInt64(Timestamp);
          }
          if (atData_ != null) {
            output.WriteRawTag(114);
            output.WriteMessage(AtData);
          }
          if (CertificationLevel != 0) {
            output.WriteRawTag(128, 1);
            output.WriteInt32(CertificationLevel);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ChatId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatId);
          }
          if (ChatType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChatType);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (ChatContent.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatContent);
          }
          if (TimestampMs != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimestampMs);
          }
          if (UnreadMessage != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnreadMessage);
          }
          if (At != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(At);
          }
          if (AvatarId != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(AvatarId);
          }
          if (AvatarUrl.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(AvatarUrl);
          }
          if (DoNotDisturb != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(DoNotDisturb);
          }
          if (Timestamp != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
          }
          if (atData_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(AtData);
          }
          if (CertificationLevel != 0) {
            size += 2 + pb::CodedOutputStream.ComputeInt32Size(CertificationLevel);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ConversationData other) {
          if (other == null) {
            return;
          }
          if (other.ChatId.Length != 0) {
            ChatId = other.ChatId;
          }
          if (other.ChatType != 0) {
            ChatType = other.ChatType;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.ChatContent.Length != 0) {
            ChatContent = other.ChatContent;
          }
          if (other.TimestampMs != 0L) {
            TimestampMs = other.TimestampMs;
          }
          if (other.UnreadMessage != 0) {
            UnreadMessage = other.UnreadMessage;
          }
          if (other.At != 0) {
            At = other.At;
          }
          if (other.AvatarId != 0L) {
            AvatarId = other.AvatarId;
          }
          if (other.AvatarUrl.Length != 0) {
            AvatarUrl = other.AvatarUrl;
          }
          if (other.DoNotDisturb != 0) {
            DoNotDisturb = other.DoNotDisturb;
          }
          if (other.Timestamp != 0L) {
            Timestamp = other.Timestamp;
          }
          if (other.atData_ != null) {
            if (atData_ == null) {
              AtData = new global::Conversation.ConversationList.Types.ConversationData.Types.AtData();
            }
            AtData.MergeFrom(other.AtData);
          }
          if (other.CertificationLevel != 0) {
            CertificationLevel = other.CertificationLevel;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                ChatId = input.ReadString();
                break;
              }
              case 16: {
                ChatType = input.ReadInt32();
                break;
              }
              case 26: {
                Name = input.ReadString();
                break;
              }
              case 34: {
                ChatContent = input.ReadString();
                break;
              }
              case 40: {
                TimestampMs = input.ReadInt64();
                break;
              }
              case 48: {
                UnreadMessage = input.ReadInt32();
                break;
              }
              case 56: {
                At = input.ReadInt32();
                break;
              }
              case 64: {
                AvatarId = input.ReadInt64();
                break;
              }
              case 74: {
                AvatarUrl = input.ReadString();
                break;
              }
              case 88: {
                DoNotDisturb = input.ReadInt32();
                break;
              }
              case 96: {
                Timestamp = input.ReadInt64();
                break;
              }
              case 114: {
                if (atData_ == null) {
                  AtData = new global::Conversation.ConversationList.Types.ConversationData.Types.AtData();
                }
                input.ReadMessage(AtData);
                break;
              }
              case 128: {
                CertificationLevel = input.ReadInt32();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                ChatId = input.ReadString();
                break;
              }
              case 16: {
                ChatType = input.ReadInt32();
                break;
              }
              case 26: {
                Name = input.ReadString();
                break;
              }
              case 34: {
                ChatContent = input.ReadString();
                break;
              }
              case 40: {
                TimestampMs = input.ReadInt64();
                break;
              }
              case 48: {
                UnreadMessage = input.ReadInt32();
                break;
              }
              case 56: {
                At = input.ReadInt32();
                break;
              }
              case 64: {
                AvatarId = input.ReadInt64();
                break;
              }
              case 74: {
                AvatarUrl = input.ReadString();
                break;
              }
              case 88: {
                DoNotDisturb = input.ReadInt32();
                break;
              }
              case 96: {
                Timestamp = input.ReadInt64();
                break;
              }
              case 114: {
                if (atData_ == null) {
                  AtData = new global::Conversation.ConversationList.Types.ConversationData.Types.AtData();
                }
                input.ReadMessage(AtData);
                break;
              }
              case 128: {
                CertificationLevel = input.ReadInt32();
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the ConversationData message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class AtData : pb::IMessage<AtData>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<AtData> _parser = new pb::MessageParser<AtData>(() => new AtData());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<AtData> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Conversation.ConversationList.Types.ConversationData.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public AtData() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public AtData(AtData other) : this() {
              unknown_ = other.unknown_;
              mentionedId_ = other.mentionedId_;
              mentionedName_ = other.mentionedName_;
              mentionedIn_ = other.mentionedIn_;
              mentionerId_ = other.mentionerId_;
              mentionerName_ = other.mentionerName_;
              msgSeq_ = other.msgSeq_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public AtData Clone() {
              return new AtData(this);
            }

            /// <summary>Field number for the "unknown" field.</summary>
            public const int UnknownFieldNumber = 1;
            private long unknown_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public long Unknown {
              get { return unknown_; }
              set {
                unknown_ = value;
              }
            }

            /// <summary>Field number for the "mentioned_id" field.</summary>
            public const int MentionedIdFieldNumber = 2;
            private string mentionedId_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string MentionedId {
              get { return mentionedId_; }
              set {
                mentionedId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "mentioned_name" field.</summary>
            public const int MentionedNameFieldNumber = 3;
            private string mentionedName_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string MentionedName {
              get { return mentionedName_; }
              set {
                mentionedName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "mentioned_in" field.</summary>
            public const int MentionedInFieldNumber = 4;
            private string mentionedIn_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string MentionedIn {
              get { return mentionedIn_; }
              set {
                mentionedIn_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "mentioner_id" field.</summary>
            public const int MentionerIdFieldNumber = 6;
            private string mentionerId_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string MentionerId {
              get { return mentionerId_; }
              set {
                mentionerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "mentioner_name" field.</summary>
            public const int MentionerNameFieldNumber = 7;
            private string mentionerName_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string MentionerName {
              get { return mentionerName_; }
              set {
                mentionerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "msg_seq" field.</summary>
            public const int MsgSeqFieldNumber = 8;
            private long msgSeq_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public long MsgSeq {
              get { return msgSeq_; }
              set {
                msgSeq_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as AtData);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(AtData other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Unknown != other.Unknown) return false;
              if (MentionedId != other.MentionedId) return false;
              if (MentionedName != other.MentionedName) return false;
              if (MentionedIn != other.MentionedIn) return false;
              if (MentionerId != other.MentionerId) return false;
              if (MentionerName != other.MentionerName) return false;
              if (MsgSeq != other.MsgSeq) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (Unknown != 0L) hash ^= Unknown.GetHashCode();
              if (MentionedId.Length != 0) hash ^= MentionedId.GetHashCode();
              if (MentionedName.Length != 0) hash ^= MentionedName.GetHashCode();
              if (MentionedIn.Length != 0) hash ^= MentionedIn.GetHashCode();
              if (MentionerId.Length != 0) hash ^= MentionerId.GetHashCode();
              if (MentionerName.Length != 0) hash ^= MentionerName.GetHashCode();
              if (MsgSeq != 0L) hash ^= MsgSeq.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (Unknown != 0L) {
                output.WriteRawTag(8);
                output.WriteInt64(Unknown);
              }
              if (MentionedId.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(MentionedId);
              }
              if (MentionedName.Length != 0) {
                output.WriteRawTag(26);
                output.WriteString(MentionedName);
              }
              if (MentionedIn.Length != 0) {
                output.WriteRawTag(34);
                output.WriteString(MentionedIn);
              }
              if (MentionerId.Length != 0) {
                output.WriteRawTag(50);
                output.WriteString(MentionerId);
              }
              if (MentionerName.Length != 0) {
                output.WriteRawTag(58);
                output.WriteString(MentionerName);
              }
              if (MsgSeq != 0L) {
                output.WriteRawTag(64);
                output.WriteInt64(MsgSeq);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (Unknown != 0L) {
                output.WriteRawTag(8);
                output.WriteInt64(Unknown);
              }
              if (MentionedId.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(MentionedId);
              }
              if (MentionedName.Length != 0) {
                output.WriteRawTag(26);
                output.WriteString(MentionedName);
              }
              if (MentionedIn.Length != 0) {
                output.WriteRawTag(34);
                output.WriteString(MentionedIn);
              }
              if (MentionerId.Length != 0) {
                output.WriteRawTag(50);
                output.WriteString(MentionerId);
              }
              if (MentionerName.Length != 0) {
                output.WriteRawTag(58);
                output.WriteString(MentionerName);
              }
              if (MsgSeq != 0L) {
                output.WriteRawTag(64);
                output.WriteInt64(MsgSeq);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (Unknown != 0L) {
                size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown);
              }
              if (MentionedId.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(MentionedId);
              }
              if (MentionedName.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(MentionedName);
              }
              if (MentionedIn.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(MentionedIn);
              }
              if (MentionerId.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(MentionerId);
              }
              if (MentionerName.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(MentionerName);
              }
              if (MsgSeq != 0L) {
                size += 1 + pb::CodedOutputStream.ComputeInt64Size(MsgSeq);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(AtData other) {
              if (other == null) {
                return;
              }
              if (other.Unknown != 0L) {
                Unknown = other.Unknown;
              }
              if (other.MentionedId.Length != 0) {
                MentionedId = other.MentionedId;
              }
              if (other.MentionedName.Length != 0) {
                MentionedName = other.MentionedName;
              }
              if (other.MentionedIn.Length != 0) {
                MentionedIn = other.MentionedIn;
              }
              if (other.MentionerId.Length != 0) {
                MentionerId = other.MentionerId;
              }
              if (other.MentionerName.Length != 0) {
                MentionerName = other.MentionerName;
              }
              if (other.MsgSeq != 0L) {
                MsgSeq = other.MsgSeq;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 8: {
                    Unknown = input.ReadInt64();
                    break;
                  }
                  case 18: {
                    MentionedId = input.ReadString();
                    break;
                  }
                  case 26: {
                    MentionedName = input.ReadString();
                    break;
                  }
                  case 34: {
                    MentionedIn = input.ReadString();
                    break;
                  }
                  case 50: {
                    MentionerId = input.ReadString();
                    break;
                  }
                  case 58: {
                    MentionerName = input.ReadString();
                    break;
                  }
                  case 64: {
                    MsgSeq = input.ReadInt64();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 8: {
                    Unknown = input.ReadInt64();
                    break;
                  }
                  case 18: {
                    MentionedId = input.ReadString();
                    break;
                  }
                  case 26: {
                    MentionedName = input.ReadString();
                    break;
                  }
                  case 34: {
                    MentionedIn = input.ReadString();
                    break;
                  }
                  case 50: {
                    MentionerId = input.ReadString();
                    break;
                  }
                  case 58: {
                    MentionerName = input.ReadString();
                    break;
                  }
                  case 64: {
                    MsgSeq = input.ReadInt64();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
