// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: friend.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Friend {

  /// <summary>Holder for reflection information generated from friend.proto</summary>
  public static partial class FriendReflection {

    #region Descriptor
    /// <summary>File descriptor for friend.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FriendReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxmcmllbmQucHJvdG8SBmZyaWVuZCIzCgZTdGF0dXMSDgoGbnVtYmVyGAEg",
            "ASgDEgwKBGNvZGUYAiABKAUSCwoDbXNnGAMgASgJIocECgxyZXF1ZXN0X2xp",
            "c3QSHgoGc3RhdHVzGAEgASgLMg4uZnJpZW5kLlN0YXR1cxIuCghyZXF1ZXN0",
            "cxgCIAMoCzIcLmZyaWVuZC5yZXF1ZXN0X2xpc3QuUmVxdWVzdBINCgV0b3Rh",
            "bBgDIAEoBRIPCgdwZW5kaW5nGAQgASgFGoYDCgdSZXF1ZXN0EhQKDHJlY2Vp",
            "dmVyTmFtZRgBIAEoCRIWCg5yZWNlaXZlckF2YXRhchgCIAEoCRIMCgRuYW1l",
            "GAMgASgJEg4KBmF2YXRhchgEIAEoCRIRCglncm91cE5hbWUYBSABKAkSEwoL",
            "Z3JvdXBBdmF0YXIYBiABKAkSEQoJaW52aXRlcklkGAcgASgJEhIKCnNvdXJj",
            "ZVR5cGUYCSABKAUSEgoKdGFyZ2V0VHlwZRgKIAEoBRIQCgh0YXJnZXRJZBgL",
            "IAEoCRISCgpyZWNlaXZlcklkGAwgASgJEg4KBnJlc3VsdBgNIAEoBRITCgtw",
            "cm9jZXNzZWRBdBgOIAEoAxIQCghpbnZpdGVBdBgQIAEoAxITCgtpbnZpdGVB",
            "dFN0chgRIAEoCRIRCglyZXF1ZXN0SWQYEiABKAUSDwoHYm90TmFtZRgTIAEo",
            "CRIRCglib3RBdmF0YXIYFCABKAkSFQoNcHJvY2Vzc29yTmFtZRgWIAEoCRIM",
            "CgRub3RlGBcgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Friend.Status), global::Friend.Status.Parser, new[]{ "Number", "Code", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Friend.request_list), global::Friend.request_list.Parser, new[]{ "Status", "Requests", "Total", "Pending" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Friend.request_list.Types.Request), global::Friend.request_list.Types.Request.Parser, new[]{ "ReceiverName", "ReceiverAvatar", "Name", "Avatar", "GroupName", "GroupAvatar", "InviterId", "SourceType", "TargetType", "TargetId", "ReceiverId", "Result", "ProcessedAt", "InviteAt", "InviteAtStr", "RequestId", "BotName", "BotAvatar", "ProcessorName", "Note" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 响应状态
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Status : pb::IMessage<Status>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Status> _parser = new pb::MessageParser<Status>(() => new Status());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Status> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Friend.FriendReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status(Status other) : this() {
      number_ = other.number_;
      code_ = other.code_;
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status Clone() {
      return new Status(this);
    }

    /// <summary>Field number for the "number" field.</summary>
    public const int NumberFieldNumber = 1;
    private long number_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Number {
      get { return number_; }
      set {
        number_ = value;
      }
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 2;
    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Status);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Status other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Number != other.Number) return false;
      if (Code != other.Code) return false;
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Number != 0L) hash ^= Number.GetHashCode();
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Number != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Number);
      }
      if (Code != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Code);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Number != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Number);
      }
      if (Code != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Code);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Number != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Number);
      }
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Status other) {
      if (other == null) {
        return;
      }
      if (other.Number != 0L) {
        Number = other.Number;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Number = input.ReadInt64();
            break;
          }
          case 16: {
            Code = input.ReadInt32();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Number = input.ReadInt64();
            break;
          }
          case 16: {
            Code = input.ReadInt32();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 对象请求列表
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class request_list : pb::IMessage<request_list>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<request_list> _parser = new pb::MessageParser<request_list>(() => new request_list());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<request_list> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Friend.FriendReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public request_list() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public request_list(request_list other) : this() {
      status_ = other.status_ != null ? other.status_.Clone() : null;
      requests_ = other.requests_.Clone();
      total_ = other.total_;
      pending_ = other.pending_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public request_list Clone() {
      return new request_list(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Friend.Status status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Friend.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "requests" field.</summary>
    public const int RequestsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Friend.request_list.Types.Request> _repeated_requests_codec
        = pb::FieldCodec.ForMessage(18, global::Friend.request_list.Types.Request.Parser);
    private readonly pbc::RepeatedField<global::Friend.request_list.Types.Request> requests_ = new pbc::RepeatedField<global::Friend.request_list.Types.Request>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Friend.request_list.Types.Request> Requests {
      get { return requests_; }
    }

    /// <summary>Field number for the "total" field.</summary>
    public const int TotalFieldNumber = 3;
    private int total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "pending" field.</summary>
    public const int PendingFieldNumber = 4;
    private int pending_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Pending {
      get { return pending_; }
      set {
        pending_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as request_list);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(request_list other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Status, other.Status)) return false;
      if(!requests_.Equals(other.requests_)) return false;
      if (Total != other.Total) return false;
      if (Pending != other.Pending) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (status_ != null) hash ^= Status.GetHashCode();
      hash ^= requests_.GetHashCode();
      if (Total != 0) hash ^= Total.GetHashCode();
      if (Pending != 0) hash ^= Pending.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (status_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Status);
      }
      requests_.WriteTo(output, _repeated_requests_codec);
      if (Total != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Total);
      }
      if (Pending != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Pending);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (status_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Status);
      }
      requests_.WriteTo(ref output, _repeated_requests_codec);
      if (Total != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Total);
      }
      if (Pending != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Pending);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (status_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      size += requests_.CalculateSize(_repeated_requests_codec);
      if (Total != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Total);
      }
      if (Pending != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pending);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(request_list other) {
      if (other == null) {
        return;
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Friend.Status();
        }
        Status.MergeFrom(other.Status);
      }
      requests_.Add(other.requests_);
      if (other.Total != 0) {
        Total = other.Total;
      }
      if (other.Pending != 0) {
        Pending = other.Pending;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (status_ == null) {
              Status = new global::Friend.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 18: {
            requests_.AddEntriesFrom(input, _repeated_requests_codec);
            break;
          }
          case 24: {
            Total = input.ReadInt32();
            break;
          }
          case 32: {
            Pending = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (status_ == null) {
              Status = new global::Friend.Status();
            }
            input.ReadMessage(Status);
            break;
          }
          case 18: {
            requests_.AddEntriesFrom(ref input, _repeated_requests_codec);
            break;
          }
          case 24: {
            Total = input.ReadInt32();
            break;
          }
          case 32: {
            Pending = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the request_list message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Request : pb::IMessage<Request>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Request> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Friend.request_list.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Request() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Request(Request other) : this() {
          receiverName_ = other.receiverName_;
          receiverAvatar_ = other.receiverAvatar_;
          name_ = other.name_;
          avatar_ = other.avatar_;
          groupName_ = other.groupName_;
          groupAvatar_ = other.groupAvatar_;
          inviterId_ = other.inviterId_;
          sourceType_ = other.sourceType_;
          targetType_ = other.targetType_;
          targetId_ = other.targetId_;
          receiverId_ = other.receiverId_;
          result_ = other.result_;
          processedAt_ = other.processedAt_;
          inviteAt_ = other.inviteAt_;
          inviteAtStr_ = other.inviteAtStr_;
          requestId_ = other.requestId_;
          botName_ = other.botName_;
          botAvatar_ = other.botAvatar_;
          processorName_ = other.processorName_;
          note_ = other.note_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Request Clone() {
          return new Request(this);
        }

        /// <summary>Field number for the "receiverName" field.</summary>
        public const int ReceiverNameFieldNumber = 1;
        private string receiverName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ReceiverName {
          get { return receiverName_; }
          set {
            receiverName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "receiverAvatar" field.</summary>
        public const int ReceiverAvatarFieldNumber = 2;
        private string receiverAvatar_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ReceiverAvatar {
          get { return receiverAvatar_; }
          set {
            receiverAvatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 3;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "avatar" field.</summary>
        public const int AvatarFieldNumber = 4;
        private string avatar_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Avatar {
          get { return avatar_; }
          set {
            avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "groupName" field.</summary>
        public const int GroupNameFieldNumber = 5;
        private string groupName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string GroupName {
          get { return groupName_; }
          set {
            groupName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "groupAvatar" field.</summary>
        public const int GroupAvatarFieldNumber = 6;
        private string groupAvatar_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string GroupAvatar {
          get { return groupAvatar_; }
          set {
            groupAvatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "inviterId" field.</summary>
        public const int InviterIdFieldNumber = 7;
        private string inviterId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string InviterId {
          get { return inviterId_; }
          set {
            inviterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "sourceType" field.</summary>
        public const int SourceTypeFieldNumber = 9;
        private int sourceType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int SourceType {
          get { return sourceType_; }
          set {
            sourceType_ = value;
          }
        }

        /// <summary>Field number for the "targetType" field.</summary>
        public const int TargetTypeFieldNumber = 10;
        private int targetType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int TargetType {
          get { return targetType_; }
          set {
            targetType_ = value;
          }
        }

        /// <summary>Field number for the "targetId" field.</summary>
        public const int TargetIdFieldNumber = 11;
        private string targetId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string TargetId {
          get { return targetId_; }
          set {
            targetId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "receiverId" field.</summary>
        public const int ReceiverIdFieldNumber = 12;
        private string receiverId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ReceiverId {
          get { return receiverId_; }
          set {
            receiverId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "result" field.</summary>
        public const int ResultFieldNumber = 13;
        private int result_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Result {
          get { return result_; }
          set {
            result_ = value;
          }
        }

        /// <summary>Field number for the "processedAt" field.</summary>
        public const int ProcessedAtFieldNumber = 14;
        private long processedAt_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long ProcessedAt {
          get { return processedAt_; }
          set {
            processedAt_ = value;
          }
        }

        /// <summary>Field number for the "inviteAt" field.</summary>
        public const int InviteAtFieldNumber = 16;
        private long inviteAt_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long InviteAt {
          get { return inviteAt_; }
          set {
            inviteAt_ = value;
          }
        }

        /// <summary>Field number for the "inviteAtStr" field.</summary>
        public const int InviteAtStrFieldNumber = 17;
        private string inviteAtStr_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string InviteAtStr {
          get { return inviteAtStr_; }
          set {
            inviteAtStr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "requestId" field.</summary>
        public const int RequestIdFieldNumber = 18;
        private int requestId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int RequestId {
          get { return requestId_; }
          set {
            requestId_ = value;
          }
        }

        /// <summary>Field number for the "botName" field.</summary>
        public const int BotNameFieldNumber = 19;
        private string botName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string BotName {
          get { return botName_; }
          set {
            botName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "botAvatar" field.</summary>
        public const int BotAvatarFieldNumber = 20;
        private string botAvatar_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string BotAvatar {
          get { return botAvatar_; }
          set {
            botAvatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "processorName" field.</summary>
        public const int ProcessorNameFieldNumber = 22;
        private string processorName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ProcessorName {
          get { return processorName_; }
          set {
            processorName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "note" field.</summary>
        public const int NoteFieldNumber = 23;
        private string note_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Note {
          get { return note_; }
          set {
            note_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Request);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Request other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ReceiverName != other.ReceiverName) return false;
          if (ReceiverAvatar != other.ReceiverAvatar) return false;
          if (Name != other.Name) return false;
          if (Avatar != other.Avatar) return false;
          if (GroupName != other.GroupName) return false;
          if (GroupAvatar != other.GroupAvatar) return false;
          if (InviterId != other.InviterId) return false;
          if (SourceType != other.SourceType) return false;
          if (TargetType != other.TargetType) return false;
          if (TargetId != other.TargetId) return false;
          if (ReceiverId != other.ReceiverId) return false;
          if (Result != other.Result) return false;
          if (ProcessedAt != other.ProcessedAt) return false;
          if (InviteAt != other.InviteAt) return false;
          if (InviteAtStr != other.InviteAtStr) return false;
          if (RequestId != other.RequestId) return false;
          if (BotName != other.BotName) return false;
          if (BotAvatar != other.BotAvatar) return false;
          if (ProcessorName != other.ProcessorName) return false;
          if (Note != other.Note) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ReceiverName.Length != 0) hash ^= ReceiverName.GetHashCode();
          if (ReceiverAvatar.Length != 0) hash ^= ReceiverAvatar.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
          if (GroupName.Length != 0) hash ^= GroupName.GetHashCode();
          if (GroupAvatar.Length != 0) hash ^= GroupAvatar.GetHashCode();
          if (InviterId.Length != 0) hash ^= InviterId.GetHashCode();
          if (SourceType != 0) hash ^= SourceType.GetHashCode();
          if (TargetType != 0) hash ^= TargetType.GetHashCode();
          if (TargetId.Length != 0) hash ^= TargetId.GetHashCode();
          if (ReceiverId.Length != 0) hash ^= ReceiverId.GetHashCode();
          if (Result != 0) hash ^= Result.GetHashCode();
          if (ProcessedAt != 0L) hash ^= ProcessedAt.GetHashCode();
          if (InviteAt != 0L) hash ^= InviteAt.GetHashCode();
          if (InviteAtStr.Length != 0) hash ^= InviteAtStr.GetHashCode();
          if (RequestId != 0) hash ^= RequestId.GetHashCode();
          if (BotName.Length != 0) hash ^= BotName.GetHashCode();
          if (BotAvatar.Length != 0) hash ^= BotAvatar.GetHashCode();
          if (ProcessorName.Length != 0) hash ^= ProcessorName.GetHashCode();
          if (Note.Length != 0) hash ^= Note.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ReceiverName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ReceiverName);
          }
          if (ReceiverAvatar.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(ReceiverAvatar);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Name);
          }
          if (Avatar.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Avatar);
          }
          if (GroupName.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(GroupName);
          }
          if (GroupAvatar.Length != 0) {
            output.WriteRawTag(50);
            output.WriteString(GroupAvatar);
          }
          if (InviterId.Length != 0) {
            output.WriteRawTag(58);
            output.WriteString(InviterId);
          }
          if (SourceType != 0) {
            output.WriteRawTag(72);
            output.WriteInt32(SourceType);
          }
          if (TargetType != 0) {
            output.WriteRawTag(80);
            output.WriteInt32(TargetType);
          }
          if (TargetId.Length != 0) {
            output.WriteRawTag(90);
            output.WriteString(TargetId);
          }
          if (ReceiverId.Length != 0) {
            output.WriteRawTag(98);
            output.WriteString(ReceiverId);
          }
          if (Result != 0) {
            output.WriteRawTag(104);
            output.WriteInt32(Result);
          }
          if (ProcessedAt != 0L) {
            output.WriteRawTag(112);
            output.WriteInt64(ProcessedAt);
          }
          if (InviteAt != 0L) {
            output.WriteRawTag(128, 1);
            output.WriteInt64(InviteAt);
          }
          if (InviteAtStr.Length != 0) {
            output.WriteRawTag(138, 1);
            output.WriteString(InviteAtStr);
          }
          if (RequestId != 0) {
            output.WriteRawTag(144, 1);
            output.WriteInt32(RequestId);
          }
          if (BotName.Length != 0) {
            output.WriteRawTag(154, 1);
            output.WriteString(BotName);
          }
          if (BotAvatar.Length != 0) {
            output.WriteRawTag(162, 1);
            output.WriteString(BotAvatar);
          }
          if (ProcessorName.Length != 0) {
            output.WriteRawTag(178, 1);
            output.WriteString(ProcessorName);
          }
          if (Note.Length != 0) {
            output.WriteRawTag(186, 1);
            output.WriteString(Note);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ReceiverName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ReceiverName);
          }
          if (ReceiverAvatar.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(ReceiverAvatar);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Name);
          }
          if (Avatar.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Avatar);
          }
          if (GroupName.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(GroupName);
          }
          if (GroupAvatar.Length != 0) {
            output.WriteRawTag(50);
            output.WriteString(GroupAvatar);
          }
          if (InviterId.Length != 0) {
            output.WriteRawTag(58);
            output.WriteString(InviterId);
          }
          if (SourceType != 0) {
            output.WriteRawTag(72);
            output.WriteInt32(SourceType);
          }
          if (TargetType != 0) {
            output.WriteRawTag(80);
            output.WriteInt32(TargetType);
          }
          if (TargetId.Length != 0) {
            output.WriteRawTag(90);
            output.WriteString(TargetId);
          }
          if (ReceiverId.Length != 0) {
            output.WriteRawTag(98);
            output.WriteString(ReceiverId);
          }
          if (Result != 0) {
            output.WriteRawTag(104);
            output.WriteInt32(Result);
          }
          if (ProcessedAt != 0L) {
            output.WriteRawTag(112);
            output.WriteInt64(ProcessedAt);
          }
          if (InviteAt != 0L) {
            output.WriteRawTag(128, 1);
            output.WriteInt64(InviteAt);
          }
          if (InviteAtStr.Length != 0) {
            output.WriteRawTag(138, 1);
            output.WriteString(InviteAtStr);
          }
          if (RequestId != 0) {
            output.WriteRawTag(144, 1);
            output.WriteInt32(RequestId);
          }
          if (BotName.Length != 0) {
            output.WriteRawTag(154, 1);
            output.WriteString(BotName);
          }
          if (BotAvatar.Length != 0) {
            output.WriteRawTag(162, 1);
            output.WriteString(BotAvatar);
          }
          if (ProcessorName.Length != 0) {
            output.WriteRawTag(178, 1);
            output.WriteString(ProcessorName);
          }
          if (Note.Length != 0) {
            output.WriteRawTag(186, 1);
            output.WriteString(Note);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ReceiverName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ReceiverName);
          }
          if (ReceiverAvatar.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ReceiverAvatar);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (Avatar.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
          }
          if (GroupName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupName);
          }
          if (GroupAvatar.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupAvatar);
          }
          if (InviterId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(InviterId);
          }
          if (SourceType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceType);
          }
          if (TargetType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetType);
          }
          if (TargetId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetId);
          }
          if (ReceiverId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ReceiverId);
          }
          if (Result != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
          }
          if (ProcessedAt != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(ProcessedAt);
          }
          if (InviteAt != 0L) {
            size += 2 + pb::CodedOutputStream.ComputeInt64Size(InviteAt);
          }
          if (InviteAtStr.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(InviteAtStr);
          }
          if (RequestId != 0) {
            size += 2 + pb::CodedOutputStream.ComputeInt32Size(RequestId);
          }
          if (BotName.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(BotName);
          }
          if (BotAvatar.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(BotAvatar);
          }
          if (ProcessorName.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(ProcessorName);
          }
          if (Note.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(Note);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Request other) {
          if (other == null) {
            return;
          }
          if (other.ReceiverName.Length != 0) {
            ReceiverName = other.ReceiverName;
          }
          if (other.ReceiverAvatar.Length != 0) {
            ReceiverAvatar = other.ReceiverAvatar;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.Avatar.Length != 0) {
            Avatar = other.Avatar;
          }
          if (other.GroupName.Length != 0) {
            GroupName = other.GroupName;
          }
          if (other.GroupAvatar.Length != 0) {
            GroupAvatar = other.GroupAvatar;
          }
          if (other.InviterId.Length != 0) {
            InviterId = other.InviterId;
          }
          if (other.SourceType != 0) {
            SourceType = other.SourceType;
          }
          if (other.TargetType != 0) {
            TargetType = other.TargetType;
          }
          if (other.TargetId.Length != 0) {
            TargetId = other.TargetId;
          }
          if (other.ReceiverId.Length != 0) {
            ReceiverId = other.ReceiverId;
          }
          if (other.Result != 0) {
            Result = other.Result;
          }
          if (other.ProcessedAt != 0L) {
            ProcessedAt = other.ProcessedAt;
          }
          if (other.InviteAt != 0L) {
            InviteAt = other.InviteAt;
          }
          if (other.InviteAtStr.Length != 0) {
            InviteAtStr = other.InviteAtStr;
          }
          if (other.RequestId != 0) {
            RequestId = other.RequestId;
          }
          if (other.BotName.Length != 0) {
            BotName = other.BotName;
          }
          if (other.BotAvatar.Length != 0) {
            BotAvatar = other.BotAvatar;
          }
          if (other.ProcessorName.Length != 0) {
            ProcessorName = other.ProcessorName;
          }
          if (other.Note.Length != 0) {
            Note = other.Note;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                ReceiverName = input.ReadString();
                break;
              }
              case 18: {
                ReceiverAvatar = input.ReadString();
                break;
              }
              case 26: {
                Name = input.ReadString();
                break;
              }
              case 34: {
                Avatar = input.ReadString();
                break;
              }
              case 42: {
                GroupName = input.ReadString();
                break;
              }
              case 50: {
                GroupAvatar = input.ReadString();
                break;
              }
              case 58: {
                InviterId = input.ReadString();
                break;
              }
              case 72: {
                SourceType = input.ReadInt32();
                break;
              }
              case 80: {
                TargetType = input.ReadInt32();
                break;
              }
              case 90: {
                TargetId = input.ReadString();
                break;
              }
              case 98: {
                ReceiverId = input.ReadString();
                break;
              }
              case 104: {
                Result = input.ReadInt32();
                break;
              }
              case 112: {
                ProcessedAt = input.ReadInt64();
                break;
              }
              case 128: {
                InviteAt = input.ReadInt64();
                break;
              }
              case 138: {
                InviteAtStr = input.ReadString();
                break;
              }
              case 144: {
                RequestId = input.ReadInt32();
                break;
              }
              case 154: {
                BotName = input.ReadString();
                break;
              }
              case 162: {
                BotAvatar = input.ReadString();
                break;
              }
              case 178: {
                ProcessorName = input.ReadString();
                break;
              }
              case 186: {
                Note = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                ReceiverName = input.ReadString();
                break;
              }
              case 18: {
                ReceiverAvatar = input.ReadString();
                break;
              }
              case 26: {
                Name = input.ReadString();
                break;
              }
              case 34: {
                Avatar = input.ReadString();
                break;
              }
              case 42: {
                GroupName = input.ReadString();
                break;
              }
              case 50: {
                GroupAvatar = input.ReadString();
                break;
              }
              case 58: {
                InviterId = input.ReadString();
                break;
              }
              case 72: {
                SourceType = input.ReadInt32();
                break;
              }
              case 80: {
                TargetType = input.ReadInt32();
                break;
              }
              case 90: {
                TargetId = input.ReadString();
                break;
              }
              case 98: {
                ReceiverId = input.ReadString();
                break;
              }
              case 104: {
                Result = input.ReadInt32();
                break;
              }
              case 112: {
                ProcessedAt = input.ReadInt64();
                break;
              }
              case 128: {
                InviteAt = input.ReadInt64();
                break;
              }
              case 138: {
                InviteAtStr = input.ReadString();
                break;
              }
              case 144: {
                RequestId = input.ReadInt32();
                break;
              }
              case 154: {
                BotName = input.ReadString();
                break;
              }
              case 162: {
                BotAvatar = input.ReadString();
                break;
              }
              case 178: {
                ProcessorName = input.ReadString();
                break;
              }
              case 186: {
                Note = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
